using System.Collections.Generic;

namespace MarcellToth.CountryDatabase
{
    public static partial class CountryDatabase
    {
        /// <summary>
        ///     Provdies a list of all countries known in the database.
        /// </summary>
        public static IEnumerable<CountryDescriptor> AllCountries { get; } = new[]
        {
            new CountryDescriptor("Afghanistan", "AF", "AFG"),
            new CountryDescriptor("Åland Islands", "AX", "ALA"),
            new CountryDescriptor("Albania", "AL", "ALB"),
            new CountryDescriptor("Algeria", "DZ", "DZA"),
            new CountryDescriptor("American Samoa", "AS", "ASM"),
            new CountryDescriptor("Andorra", "AD", "AND"),
            new CountryDescriptor("Angola", "AO", "AGO"),
            new CountryDescriptor("Anguilla", "AI", "AIA"),
            new CountryDescriptor("Antarctica", "AQ", "ATA"),
            new CountryDescriptor("Antigua and Barbuda", "AG", "ATG"),
            new CountryDescriptor("Argentina", "AR", "ARG"),
            new CountryDescriptor("Armenia", "AM", "ARM"),
            new CountryDescriptor("Aruba", "AW", "ABW"),
            new CountryDescriptor("Australia", "AU", "AUS"),
            new CountryDescriptor("Austria", "AT", "AUT"),
            new CountryDescriptor("Azerbaijan", "AZ", "AZE"),
            new CountryDescriptor("Bahamas", "BS", "BHS"),
            new CountryDescriptor("Bahrain", "BH", "BHR"),
            new CountryDescriptor("Bangladesh", "BD", "BGD"),
            new CountryDescriptor("Barbados", "BB", "BRB"),
            new CountryDescriptor("Belarus", "BY", "BLR"),
            new CountryDescriptor("Belgium", "BE", "BEL"),
            new CountryDescriptor("Belize", "BZ", "BLZ"),
            new CountryDescriptor("Benin", "BJ", "BEN"),
            new CountryDescriptor("Bermuda", "BM", "BMU"),
            new CountryDescriptor("Bhutan", "BT", "BTN"),
            new CountryDescriptor("Bolivia, Plurinational State of)", "BO", "BOL"),
            new CountryDescriptor("Bonaire, Sint Eustatius and Saba", "BQ", "BES"),
            new CountryDescriptor("Bosnia and Herzegovina", "BA", "BIH"),
            new CountryDescriptor("Botswana", "BW", "BWA"),
            new CountryDescriptor("Bouvet Island", "BV", "BVT"),
            new CountryDescriptor("Brazil", "BR", "BRA"),
            new CountryDescriptor("British Indian Ocean Territory", "IO", "IOT"),
            new CountryDescriptor("Brunei Darussalam", "BN", "BRN"),
            new CountryDescriptor("Bulgaria", "BG", "BGR"),
            new CountryDescriptor("Burkina Faso", "BF", "BFA"),
            new CountryDescriptor("Burundi", "BI", "BDI"),
            new CountryDescriptor("Cabo Verde", "CV", "CPV"),
            new CountryDescriptor("Cambodia", "KH", "KHM"),
            new CountryDescriptor("Cameroon", "CM", "CMR"),
            new CountryDescriptor("Canada", "CA", "CAN"),
            new CountryDescriptor("Cayman Islands", "KY", "CYM"),
            new CountryDescriptor("Central African Republic", "CF", "CAF"),
            new CountryDescriptor("Chad", "TD", "TCD"),
            new CountryDescriptor("Chile", "CL", "CHL"),
            new CountryDescriptor("China", "CN", "CHN"),
            new CountryDescriptor("Christmas Island", "CX", "CXR"),
            new CountryDescriptor("Cocos, Keeling) Islands", "CC", "CCK"),
            new CountryDescriptor("Colombia", "CO", "COL"),
            new CountryDescriptor("Comoros", "KM", "COM"),
            new CountryDescriptor("Congo", "CG", "COG"),
            new CountryDescriptor("Congo, Democratic Republic", "CD", "COD"),
            new CountryDescriptor("Cook Islands", "CK", "COK"),
            new CountryDescriptor("Costa Rica", "CR", "CRI"),
            new CountryDescriptor("Côte d'Ivoire", "CI", "CIV"),
            new CountryDescriptor("Croatia", "HR", "HRV"),
            new CountryDescriptor("Cuba", "CU", "CUB"),
            new CountryDescriptor("Curaçao", "CW", "CUW"),
            new CountryDescriptor("Cyprus", "CY", "CYP"),
            new CountryDescriptor("Czechia", "CZ", "CZE"),
            new CountryDescriptor("Denmark", "DK", "DNK"),
            new CountryDescriptor("Djibouti", "DJ", "DJI"),
            new CountryDescriptor("Dominica", "DM", "DMA"),
            new CountryDescriptor("Dominican Republic", "DO", "DOM"),
            new CountryDescriptor("Ecuador", "EC", "ECU"),
            new CountryDescriptor("Egypt", "EG", "EGY"),
            new CountryDescriptor("El Salvador", "SV", "SLV"),
            new CountryDescriptor("Equatorial Guinea", "GQ", "GNQ"),
            new CountryDescriptor("Eritrea", "ER", "ERI"),
            new CountryDescriptor("Estonia", "EE", "EST"),
            new CountryDescriptor("Ethiopia", "ET", "ETH"),
            new CountryDescriptor("Falkland Islands, Malvinas)", "FK", "FLK"),
            new CountryDescriptor("Faroe Islands", "FO", "FRO"),
            new CountryDescriptor("Fiji", "FJ", "FJI"),
            new CountryDescriptor("Finland", "FI", "FIN"),
            new CountryDescriptor("France", "FR", "FRA"),
            new CountryDescriptor("French Guiana", "GF", "GUF"),
            new CountryDescriptor("French Polynesia", "PF", "PYF"),
            new CountryDescriptor("French Southern Territories", "TF", "ATF"),
            new CountryDescriptor("Gabon", "GA", "GAB"),
            new CountryDescriptor("Gambia", "GM", "GMB"),
            new CountryDescriptor("Georgia", "GE", "GEO"),
            new CountryDescriptor("Germany", "DE", "DEU"),
            new CountryDescriptor("Ghana", "GH", "GHA"),
            new CountryDescriptor("Gibraltar", "GI", "GIB"),
            new CountryDescriptor("Greece", "GR", "GRC"),
            new CountryDescriptor("Greenland", "GL", "GRL"),
            new CountryDescriptor("Grenada", "GD", "GRD"),
            new CountryDescriptor("Guadeloupe", "GP", "GLP"),
            new CountryDescriptor("Guam", "GU", "GUM"),
            new CountryDescriptor("Guatemala", "GT", "GTM"),
            new CountryDescriptor("Guernsey", "GG", "GGY"),
            new CountryDescriptor("Guinea", "GN", "GIN"),
            new CountryDescriptor("Guinea-Bissau", "GW", "GNB"),
            new CountryDescriptor("Guyana", "GY", "GUY"),
            new CountryDescriptor("Haiti", "HT", "HTI"),
            new CountryDescriptor("Heard Island and McDonald Islands", "HM", "HMD"),
            new CountryDescriptor("Holy See", "VA", "VAT"),
            new CountryDescriptor("Honduras", "HN", "HND"),
            new CountryDescriptor("Hong Kong", "HK", "HKG"),
            new CountryDescriptor("Hungary", "HU", "HUN"),
            new CountryDescriptor("Iceland", "IS", "ISL"),
            new CountryDescriptor("India", "IN", "IND"),
            new CountryDescriptor("Indonesia", "ID", "IDN"),
            new CountryDescriptor("Iran, Islamic Republic of)", "IR", "IRN"),
            new CountryDescriptor("Iraq", "IQ", "IRQ"),
            new CountryDescriptor("Ireland", "IE", "IRL"),
            new CountryDescriptor("Isle of Man", "IM", "IMN"),
            new CountryDescriptor("Israel", "IL", "ISR"),
            new CountryDescriptor("Italy", "IT", "ITA"),
            new CountryDescriptor("Jamaica", "JM", "JAM"),
            new CountryDescriptor("Japan", "JP", "JPN"),
            new CountryDescriptor("Jersey", "JE", "JEY"),
            new CountryDescriptor("Jordan", "JO", "JOR"),
            new CountryDescriptor("Kazakhstan", "KZ", "KAZ"),
            new CountryDescriptor("Kenya", "KE", "KEN"),
            new CountryDescriptor("Kiribati", "KI", "KIR"),
            new CountryDescriptor("Korea, Democratic People's Republic of)", "KP", "PRK"),
            new CountryDescriptor("Korea, Republic of)", "KR", "KOR"),
            new CountryDescriptor("Kuwait", "KW", "KWT"),
            new CountryDescriptor("Kyrgyzstan", "KG", "KGZ"),
            new CountryDescriptor("Lao People's Democratic Republic", "LA", "LAO"),
            new CountryDescriptor("Latvia", "LV", "LVA"),
            new CountryDescriptor("Lebanon", "LB", "LBN"),
            new CountryDescriptor("Lesotho", "LS", "LSO"),
            new CountryDescriptor("Liberia", "LR", "LBR"),
            new CountryDescriptor("Libya", "LY", "LBY"),
            new CountryDescriptor("Liechtenstein", "LI", "LIE"),
            new CountryDescriptor("Lithuania", "LT", "LTU"),
            new CountryDescriptor("Luxembourg", "LU", "LUX"),
            new CountryDescriptor("Macao", "MO", "MAC"),
            new CountryDescriptor("Macedonia, the former Yugoslav Republic of)", "MK", "MKD"),
            new CountryDescriptor("Madagascar", "MG", "MDG"),
            new CountryDescriptor("Malawi", "MW", "MWI"),
            new CountryDescriptor("Malaysia", "MY", "MYS"),
            new CountryDescriptor("Maldives", "MV", "MDV"),
            new CountryDescriptor("Mali", "ML", "MLI"),
            new CountryDescriptor("Malta", "MT", "MLT"),
            new CountryDescriptor("Marshall Islands", "MH", "MHL"),
            new CountryDescriptor("Martinique", "MQ", "MTQ"),
            new CountryDescriptor("Mauritania", "MR", "MRT"),
            new CountryDescriptor("Mauritius", "MU", "MUS"),
            new CountryDescriptor("Mayotte", "YT", "MYT"),
            new CountryDescriptor("Mexico", "MX", "MEX"),
            new CountryDescriptor("Micronesia, Federated States of)", "FM", "FSM"),
            new CountryDescriptor("Moldova, Republic of)", "MD", "MDA"),
            new CountryDescriptor("Monaco", "MC", "MCO"),
            new CountryDescriptor("Mongolia", "MN", "MNG"),
            new CountryDescriptor("Montenegro", "ME", "MNE"),
            new CountryDescriptor("Montserrat", "MS", "MSR"),
            new CountryDescriptor("Morocco", "MA", "MAR"),
            new CountryDescriptor("Mozambique", "MZ", "MOZ"),
            new CountryDescriptor("Myanmar", "MM", "MMR"),
            new CountryDescriptor("Namibia", "NA", "NAM"),
            new CountryDescriptor("Nauru", "NR", "NRU"),
            new CountryDescriptor("Nepal", "NP", "NPL"),
            new CountryDescriptor("Netherlands", "NL", "NLD"),
            new CountryDescriptor("New Caledonia", "NC", "NCL"),
            new CountryDescriptor("New Zealand", "NZ", "NZL"),
            new CountryDescriptor("Nicaragua", "NI", "NIC"),
            new CountryDescriptor("Niger", "NE", "NER"),
            new CountryDescriptor("Nigeria", "NG", "NGA"),
            new CountryDescriptor("Niue", "NU", "NIU"),
            new CountryDescriptor("Norfolk Island", "NF", "NFK"),
            new CountryDescriptor("Northern Mariana Islands", "MP", "MNP"),
            new CountryDescriptor("Norway", "NO", "NOR"),
            new CountryDescriptor("Oman", "OM", "OMN"),
            new CountryDescriptor("Pakistan", "PK", "PAK"),
            new CountryDescriptor("Palau", "PW", "PLW"),
            new CountryDescriptor("Palestine, State of", "PS", "PSE"),
            new CountryDescriptor("Panama", "PA", "PAN"),
            new CountryDescriptor("Papua New Guinea", "PG", "PNG"),
            new CountryDescriptor("Paraguay", "PY", "PRY"),
            new CountryDescriptor("Peru", "PE", "PER"),
            new CountryDescriptor("Philippines", "PH", "PHL"),
            new CountryDescriptor("Pitcairn", "PN", "PCN"),
            new CountryDescriptor("Poland", "PL", "POL"),
            new CountryDescriptor("Portugal", "PT", "PRT"),
            new CountryDescriptor("Puerto Rico", "PR", "PRI"),
            new CountryDescriptor("Qatar", "QA", "QAT"),
            new CountryDescriptor("Réunion", "RE", "REU"),
            new CountryDescriptor("Romania", "RO", "ROU"),
            new CountryDescriptor("Russian Federation", "RU", "RUS"),
            new CountryDescriptor("Rwanda", "RW", "RWA"),
            new CountryDescriptor("Saint Barthélemy", "BL", "BLM"),
            new CountryDescriptor("Saint Helena, Ascension and Tristan da Cunha", "SH", "SHN"),
            new CountryDescriptor("Saint Kitts and Nevis", "KN", "KNA"),
            new CountryDescriptor("Saint Lucia", "LC", "LCA"),
            new CountryDescriptor("Saint Martin, French part)", "MF", "MAF"),
            new CountryDescriptor("Saint Pierre and Miquelon", "PM", "SPM"),
            new CountryDescriptor("Saint Vincent and the Grenadines", "VC", "VCT"),
            new CountryDescriptor("Samoa", "WS", "WSM"),
            new CountryDescriptor("San Marino", "SM", "SMR"),
            new CountryDescriptor("Sao Tome and Principe", "ST", "STP"),
            new CountryDescriptor("Saudi Arabia", "SA", "SAU"),
            new CountryDescriptor("Senegal", "SN", "SEN"),
            new CountryDescriptor("Serbia", "RS", "SRB"),
            new CountryDescriptor("Seychelles", "SC", "SYC"),
            new CountryDescriptor("Sierra Leone", "SL", "SLE"),
            new CountryDescriptor("Singapore", "SG", "SGP"),
            new CountryDescriptor("Sint Maarten, Dutch part)", "SX", "SXM"),
            new CountryDescriptor("Slovakia", "SK", "SVK"),
            new CountryDescriptor("Slovenia", "SI", "SVN"),
            new CountryDescriptor("Solomon Islands", "SB", "SLB"),
            new CountryDescriptor("Somalia", "SO", "SOM"),
            new CountryDescriptor("South Africa", "ZA", "ZAF"),
            new CountryDescriptor("South Georgia and the South Sandwich Islands", "GS", "SGS"),
            new CountryDescriptor("South Sudan", "SS", "SSD"),
            new CountryDescriptor("Spain", "ES", "ESP"),
            new CountryDescriptor("Sri Lanka", "LK", "LKA"),
            new CountryDescriptor("Sudan", "SD", "SDN"),
            new CountryDescriptor("Suriname", "SR", "SUR"),
            new CountryDescriptor("Svalbard and Jan Mayen", "SJ", "SJM"),
            new CountryDescriptor("Swaziland", "SZ", "SWZ"),
            new CountryDescriptor("Sweden", "SE", "SWE"),
            new CountryDescriptor("Switzerland", "CH", "CHE"),
            new CountryDescriptor("Syrian Arab Republic", "SY", "SYR"),
            new CountryDescriptor("Taiwan", "TW", "TWN"),
            new CountryDescriptor("Tajikistan", "TJ", "TJK"),
            new CountryDescriptor("Tanzania, United Republic of", "TZ", "TZA"),
            new CountryDescriptor("Thailand", "TH", "THA"),
            new CountryDescriptor("Timor-Leste", "TL", "TLS"),
            new CountryDescriptor("Togo", "TG", "TGO"),
            new CountryDescriptor("Tokelau", "TK", "TKL"),
            new CountryDescriptor("Tonga", "TO", "TON"),
            new CountryDescriptor("Trinidad and Tobago", "TT", "TTO"),
            new CountryDescriptor("Tunisia", "TN", "TUN"),
            new CountryDescriptor("Turkey", "TR", "TUR"),
            new CountryDescriptor("Turkmenistan", "TM", "TKM"),
            new CountryDescriptor("Turks and Caicos Islands", "TC", "TCA"),
            new CountryDescriptor("Tuvalu", "TV", "TUV"),
            new CountryDescriptor("Uganda", "UG", "UGA"),
            new CountryDescriptor("Ukraine", "UA", "UKR"),
            new CountryDescriptor("United Arab Emirates", "AE", "ARE"),
            new CountryDescriptor("United Kingdom", "GB", "GBR"),
            new CountryDescriptor("United States of America", "US", "USA"),
            new CountryDescriptor("United States Minor Outlying Islands", "UM", "UMI"),
            new CountryDescriptor("Uruguay", "UY", "URY"),
            new CountryDescriptor("Uzbekistan", "UZ", "UZB"),
            new CountryDescriptor("Vanuatu", "VU", "VUT"),
            new CountryDescriptor("Venezuela", "VE", "VEN"),
            new CountryDescriptor("Viet Nam", "VN", "VNM"),
            new CountryDescriptor("Virgin Islands, British)", "VG", "VGB"),
            new CountryDescriptor("Virgin Islands, U.S.)", "VI", "VIR"),
            new CountryDescriptor("Wallis and Futuna", "WF", "WLF"),
            new CountryDescriptor("Western Sahara", "EH", "ESH"),
            new CountryDescriptor("Yemen", "YE", "YEM"),
            new CountryDescriptor("Zambia", "ZM", "ZMB"),
            new CountryDescriptor("Zimbabwe", "ZW", "ZWE")
        };
    }
}